[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

# Disable secrets scanning for expected public environment variables
# These NEXT_PUBLIC_ variables are meant to be exposed to the client
[secrets]
  scan_omit_keys = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY", 
    "NEXT_PUBLIC_CURRENCY_API_KEY"
  ]

# Headers for better caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Next.js image optimization
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images"
  status = 200
  query = {url = ":url", w = ":width", q = ":quality"}
